--------------------------------------------------------
--  File created - Saturday-August-17-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence DEMO_CUST_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DEMO_CUST_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_ORDER_ITEMS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DEMO_ORDER_ITEMS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_ORD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DEMO_ORD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_PROD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DEMO_PROD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_USERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DEMO_USERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table RESULT
--------------------------------------------------------

  CREATE TABLE "RESULT" 
   (	"EXAM" VARCHAR2(60 BYTE), 
	"ADMISSIONNO" VARCHAR2(10 BYTE), 
	"NAME" VARCHAR2(60 BYTE), 
	"CLASS" VARCHAR2(7 BYTE), 
	"SECTION" CHAR(1 BYTE), 
	"ROLLNO" VARCHAR2(10 BYTE), 
	"MATHS" VARCHAR2(10 BYTE), 
	"SCIENCE_EVS" VARCHAR2(10 BYTE), 
	"SOCIALSCIENCE" VARCHAR2(10 BYTE), 
	"ENGLISH" VARCHAR2(10 BYTE), 
	"HINDI" VARCHAR2(10 BYTE), 
	"SANSKRIT" VARCHAR2(10 BYTE), 
	"COMPUTER" VARCHAR2(10 BYTE), 
	"GK" VARCHAR2(10 BYTE), 
	"TOTAL" VARCHAR2(10 BYTE), 
	"PERCENTAGE" VARCHAR2(10 BYTE), 
	"AVERAGE" VARCHAR2(10 BYTE), 
	"DRAWING" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STUDENT
--------------------------------------------------------

  CREATE TABLE "STUDENT" 
   (	"ADMNO" VARCHAR2(10 BYTE), 
	"NAME" VARCHAR2(60 BYTE), 
	"CLASS" VARCHAR2(7 BYTE), 
	"SECTION" CHAR(1 BYTE), 
	"ROLLNO" VARCHAR2(10 BYTE), 
	"DOB" DATE, 
	"MOBILENO" VARCHAR2(10 BYTE), 
	"FNAME" VARCHAR2(60 BYTE), 
	"MNAME" VARCHAR2(60 BYTE), 
	"CATEGORY" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(250 BYTE), 
	"ADHAR" VARCHAR2(12 BYTE), 
	"SSSMID" VARCHAR2(40 BYTE), 
	"REMARKS" VARCHAR2(300 BYTE), 
	"GENDER" VARCHAR2(15 BYTE), 
	"FEEMONTH" NUMBER, 
	"FEEYEAR" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ADMISSION
--------------------------------------------------------

  CREATE TABLE "ADMISSION" 
   (	"ADM_NO" VARCHAR2(10 BYTE), 
	"DATE_OF_ADMISSION" DATE, 
	"FIRST_NAME" VARCHAR2(25 BYTE), 
	"MIDDLE_NAME" VARCHAR2(25 BYTE), 
	"LAST_NAME" VARCHAR2(25 BYTE), 
	"GENDER" VARCHAR2(11 BYTE), 
	"DATE_OF_BIRTH" DATE, 
	"CLASS" VARCHAR2(7 BYTE), 
	"SECTION" CHAR(1 BYTE), 
	"MOB_NO" VARCHAR2(10 BYTE), 
	"FATHER_NAME" VARCHAR2(50 BYTE), 
	"MOTHER_NAME" VARCHAR2(50 BYTE), 
	"CATEGORY" VARCHAR2(20 BYTE), 
	"NATIONALITY" VARCHAR2(20 BYTE), 
	"STATE" VARCHAR2(25 BYTE), 
	"ADDRESS" VARCHAR2(250 BYTE), 
	"ADHAR_NO" VARCHAR2(12 BYTE), 
	"SSSMID_NO" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CLASSDETAIL
--------------------------------------------------------

  CREATE TABLE "CLASSDETAIL" 
   (	"CLASS" VARCHAR2(7 BYTE), 
	"SECTION" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into RESULT
SET DEFINE OFF;
Insert into RESULT (EXAM,ADMISSIONNO,NAME,CLASS,SECTION,ROLLNO,MATHS,SCIENCE_EVS,SOCIALSCIENCE,ENGLISH,HINDI,SANSKRIT,COMPUTER,GK,TOTAL,PERCENTAGE,AVERAGE,DRAWING) values ('BAFJFDAJK','1','AS','5','A','1','100','0','0','0','0','0','0','0','100.0','12.5','12.5','NA');
REM INSERTING into STUDENT
SET DEFINE OFF;
Insert into STUDENT (ADMNO,NAME,CLASS,SECTION,ROLLNO,DOB,MOBILENO,FNAME,MNAME,CATEGORY,ADDRESS,ADHAR,SSSMID,REMARKS,GENDER,FEEMONTH,FEEYEAR) values ('1','PRADEEP KUMAR LOHARE','8','A','1',to_date('04-12-00','DD-MM-RR'),'6265105303','PRADEEP FATHER','PRADEEP MOOTHER','OBC','BHOPAL','000000000000','10','GOOD','Male',null,null);
REM INSERTING into ADMISSION
SET DEFINE OFF;
Insert into ADMISSION (ADM_NO,DATE_OF_ADMISSION,FIRST_NAME,MIDDLE_NAME,LAST_NAME,GENDER,DATE_OF_BIRTH,CLASS,SECTION,MOB_NO,FATHER_NAME,MOTHER_NAME,CATEGORY,NATIONALITY,STATE,ADDRESS,ADHAR_NO,SSSMID_NO) values ('1',to_date('13-08-19','DD-MM-RR'),'PRADEEP','KUMAR','LOHARE','Male',to_date('04-12-00','DD-MM-RR'),'1','A','6265105303','FATHER OF PRADEEP','MOTHER OF [RADEEP','OBC','INDIAN','MP','BHOPAL','000000000000','10');
Insert into ADMISSION (ADM_NO,DATE_OF_ADMISSION,FIRST_NAME,MIDDLE_NAME,LAST_NAME,GENDER,DATE_OF_BIRTH,CLASS,SECTION,MOB_NO,FATHER_NAME,MOTHER_NAME,CATEGORY,NATIONALITY,STATE,ADDRESS,ADHAR_NO,SSSMID_NO) values ('3',to_date('16-08-19','DD-MM-RR'),'RISHABH',null,'KUMAR','Male',to_date('30-08-19','DD-MM-RR'),'1','A','6265105303','RISHABH FATHER','RISHABH MOTHER','Gen','INDIAN','MP','BHOPAL','333333333333','30');
REM INSERTING into CLASSDETAIL
SET DEFINE OFF;
Insert into CLASSDETAIL (CLASS,SECTION) values ('4','A');
Insert into CLASSDETAIL (CLASS,SECTION) values ('KG-II','A');
Insert into CLASSDETAIL (CLASS,SECTION) values ('5','A');
Insert into CLASSDETAIL (CLASS,SECTION) values ('KG-I','A');
Insert into CLASSDETAIL (CLASS,SECTION) values ('8','A');
Insert into CLASSDETAIL (CLASS,SECTION) values ('6','A');
Insert into CLASSDETAIL (CLASS,SECTION) values ('7','A');
Insert into CLASSDETAIL (CLASS,SECTION) values ('1','A');
Insert into CLASSDETAIL (CLASS,SECTION) values ('2','A');
Insert into CLASSDETAIL (CLASS,SECTION) values ('3','A');
--------------------------------------------------------
--  DDL for Index ADMISSION_CON
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMISSION_CON" ON "ADMISSION" ("ADHAR_NO", "SSSMID_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ADMISSION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMISSION_PK" ON "ADMISSION" ("ADM_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ADMISSION_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMISSION_UK1" ON "ADMISSION" ("ADHAR_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RESULT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RESULT_PK" ON "RESULT" ("ADMISSIONNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STUDENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENT_PK" ON "STUDENT" ("ADMNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STUDENT_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENT_UK1" ON "STUDENT" ("ADHAR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Function CUSTOM_AUTH
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "CUSTOM_AUTH" (p_username in VARCHAR2, p_password in VARCHAR2)
return BOOLEAN
is
  l_password varchar2(4000);
  l_stored_password varchar2(4000);
  l_expires_on date;
  l_count number;
begin
-- First, check to see if the user is in the user table
select count(*) into l_count from demo_users where user_name = p_username;
if l_count > 0 then
  -- First, we fetch the stored hashed password & expire date
  select password, expires_on into l_stored_password, l_expires_on
   from demo_users where user_name = p_username;

  -- Next, we check to see if the user's account is expired
  -- If it is, return FALSE
  if l_expires_on > sysdate or l_expires_on is null then

    -- If the account is not expired, we have to apply the custom hash
    -- function to the password
    l_password := custom_hash(p_username, p_password);

    -- Finally, we compare them to see if they are the same and return
    -- either TRUE or FALSE
    if l_password = l_stored_password then
      return true;
    else
      return false;
    end if;
  else
    return false;
  end if;
else
  -- The username provided is not in the DEMO_USERS table
  return false;
end if;
end;

/
--------------------------------------------------------
--  DDL for Function CUSTOM_HASH
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "CUSTOM_HASH" (p_username in varchar2, p_password in varchar2)
return varchar2
is
  l_password varchar2(4000);
  l_salt varchar2(4000) := 'QF0CAP9U4LVXXPQCLMZJRIMSRVT93S';
begin

-- This function should be wrapped, as the hash algorhythm is exposed here.
-- You can change the value of l_salt or the method of which to call the
-- DBMS_OBFUSCATOIN toolkit, but you much reset all of your passwords
-- if you choose to do this.

l_password := utl_raw.cast_to_raw(dbms_obfuscation_toolkit.md5
  (input_string => p_password || substr(l_salt,10,13) || p_username ||
    substr(l_salt, 4,10)));
return l_password;
end;

/
--------------------------------------------------------
--  Constraints for Table RESULT
--------------------------------------------------------

  ALTER TABLE "RESULT" MODIFY ("DRAWING" NOT NULL ENABLE);
  ALTER TABLE "RESULT" ADD CONSTRAINT "RESULT_PK" PRIMARY KEY ("ADMISSIONNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "RESULT" MODIFY ("AVERAGE" NOT NULL ENABLE);
  ALTER TABLE "RESULT" MODIFY ("PERCENTAGE" NOT NULL ENABLE);
  ALTER TABLE "RESULT" MODIFY ("TOTAL" NOT NULL ENABLE);
  ALTER TABLE "RESULT" MODIFY ("GK" NOT NULL ENABLE);
  ALTER TABLE "RESULT" MODIFY ("COMPUTER" NOT NULL ENABLE);
  ALTER TABLE "RESULT" MODIFY ("SANSKRIT" NOT NULL ENABLE);
  ALTER TABLE "RESULT" MODIFY ("HINDI" NOT NULL ENABLE);
  ALTER TABLE "RESULT" MODIFY ("ENGLISH" NOT NULL ENABLE);
  ALTER TABLE "RESULT" MODIFY ("SOCIALSCIENCE" NOT NULL ENABLE);
  ALTER TABLE "RESULT" MODIFY ("SCIENCE_EVS" NOT NULL ENABLE);
  ALTER TABLE "RESULT" MODIFY ("MATHS" NOT NULL ENABLE);
  ALTER TABLE "RESULT" MODIFY ("ROLLNO" NOT NULL ENABLE);
  ALTER TABLE "RESULT" MODIFY ("SECTION" NOT NULL ENABLE);
  ALTER TABLE "RESULT" MODIFY ("CLASS" NOT NULL ENABLE);
  ALTER TABLE "RESULT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "RESULT" MODIFY ("ADMISSIONNO" NOT NULL ENABLE);
  ALTER TABLE "RESULT" MODIFY ("EXAM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "STUDENT" ADD CONSTRAINT "STUDENT_UK1" UNIQUE ("ADHAR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "STUDENT" ADD CONSTRAINT "STUDENT_PK" PRIMARY KEY ("ADMNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "STUDENT" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "STUDENT" MODIFY ("SSSMID" NOT NULL ENABLE);
  ALTER TABLE "STUDENT" MODIFY ("ADHAR" NOT NULL ENABLE);
  ALTER TABLE "STUDENT" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "STUDENT" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "STUDENT" MODIFY ("MNAME" NOT NULL ENABLE);
  ALTER TABLE "STUDENT" MODIFY ("FNAME" NOT NULL ENABLE);
  ALTER TABLE "STUDENT" MODIFY ("MOBILENO" NOT NULL ENABLE);
  ALTER TABLE "STUDENT" MODIFY ("DOB" NOT NULL ENABLE);
  ALTER TABLE "STUDENT" MODIFY ("ROLLNO" NOT NULL ENABLE);
  ALTER TABLE "STUDENT" MODIFY ("SECTION" NOT NULL ENABLE);
  ALTER TABLE "STUDENT" MODIFY ("CLASS" NOT NULL ENABLE);
  ALTER TABLE "STUDENT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "STUDENT" MODIFY ("ADMNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADMISSION
--------------------------------------------------------

  ALTER TABLE "ADMISSION" ADD CONSTRAINT "ADMISSION_CON" UNIQUE ("ADHAR_NO", "SSSMID_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ADMISSION" ADD CONSTRAINT "ADMISSION_UK1" UNIQUE ("ADHAR_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ADMISSION" ADD CONSTRAINT "ADMISSION_PK" PRIMARY KEY ("ADM_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ADMISSION" MODIFY ("SSSMID_NO" NOT NULL ENABLE);
  ALTER TABLE "ADMISSION" MODIFY ("ADHAR_NO" NOT NULL ENABLE);
  ALTER TABLE "ADMISSION" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "ADMISSION" MODIFY ("STATE" NOT NULL ENABLE);
  ALTER TABLE "ADMISSION" MODIFY ("NATIONALITY" NOT NULL ENABLE);
  ALTER TABLE "ADMISSION" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "ADMISSION" MODIFY ("MOTHER_NAME" NOT NULL ENABLE);
  ALTER TABLE "ADMISSION" MODIFY ("FATHER_NAME" NOT NULL ENABLE);
  ALTER TABLE "ADMISSION" MODIFY ("MOB_NO" NOT NULL ENABLE);
  ALTER TABLE "ADMISSION" MODIFY ("SECTION" NOT NULL ENABLE);
  ALTER TABLE "ADMISSION" MODIFY ("CLASS" NOT NULL ENABLE);
  ALTER TABLE "ADMISSION" MODIFY ("DATE_OF_BIRTH" NOT NULL ENABLE);
  ALTER TABLE "ADMISSION" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "ADMISSION" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "ADMISSION" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "ADMISSION" MODIFY ("DATE_OF_ADMISSION" NOT NULL ENABLE);
  ALTER TABLE "ADMISSION" MODIFY ("ADM_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLASSDETAIL
--------------------------------------------------------

  ALTER TABLE "CLASSDETAIL" MODIFY ("SECTION" NOT NULL ENABLE);
  ALTER TABLE "CLASSDETAIL" MODIFY ("CLASS" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table RESULT
--------------------------------------------------------

  ALTER TABLE "RESULT" ADD CONSTRAINT "RESULT_CON" FOREIGN KEY ("ADMISSIONNO")
	  REFERENCES "STUDENT" ("ADMNO") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "STUDENT" ADD CONSTRAINT "STUDENT_ADMISSION_RELATION" FOREIGN KEY ("ADMNO")
	  REFERENCES "ADMISSION" ("ADM_NO") ON DELETE CASCADE ENABLE;
